// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file csgo_econ_preview.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file csgo_econ_preview.proto.
 */
export const file_csgo_econ_preview: GenFile = /*@__PURE__*/
  fileDesc("Chdjc2dvX2Vjb25fcHJldmlldy5wcm90byK0CQoZQ0Vjb25JdGVtUHJldmlld0RhdGFCbG9jaxIWCglhY2NvdW50aWQYASABKA1IAIgBARITCgZpdGVtaWQYAiABKARIAYgBARIVCghkZWZpbmRleBgDIAEoDUgCiAEBEhcKCnBhaW50aW5kZXgYBCABKA1IA4gBARITCgZyYXJpdHkYBSABKA1IBIgBARIUCgdxdWFsaXR5GAYgASgNSAWIAQESFgoJcGFpbnR3ZWFyGAcgASgNSAaIAQESFgoJcGFpbnRzZWVkGAggASgNSAeIAQESHwoSa2lsbGVhdGVyc2NvcmV0eXBlGAkgASgNSAiIAQESGwoOa2lsbGVhdGVydmFsdWUYCiABKA1ICYgBARIXCgpjdXN0b21uYW1lGAsgASgJSAqIAQESNAoIc3RpY2tlcnMYDCADKAsyIi5DRWNvbkl0ZW1QcmV2aWV3RGF0YUJsb2NrLlN0aWNrZXISFgoJaW52ZW50b3J5GA0gASgNSAuIAQESEwoGb3JpZ2luGA4gASgNSAyIAQESFAoHcXVlc3RpZBgPIAEoDUgNiAEBEhcKCmRyb3ByZWFzb24YECABKA1IDogBARIXCgptdXNpY2luZGV4GBEgASgNSA+IAQESFQoIZW50aW5kZXgYEiABKAVIEIgBARIVCghwZXRpbmRleBgTIAEoDUgRiAEBEjUKCWtleWNoYWlucxgUIAMoCzIiLkNFY29uSXRlbVByZXZpZXdEYXRhQmxvY2suU3RpY2tlchISCgVzdHlsZRgVIAEoDUgSiAEBGtsCCgdTdGlja2VyEhEKBHNsb3QYASABKA1IAIgBARIXCgpzdGlja2VyX2lkGAIgASgNSAGIAQESEQoEd2VhchgDIAEoAkgCiAEBEhIKBXNjYWxlGAQgASgCSAOIAQESFQoIcm90YXRpb24YBSABKAJIBIgBARIUCgd0aW50X2lkGAYgASgNSAWIAQESFQoIb2Zmc2V0X3gYByABKAJIBogBARIVCghvZmZzZXRfeRgIIAEoAkgHiAEBEhUKCG9mZnNldF96GAkgASgCSAiIAQESFAoHcGF0dGVybhgKIAEoDUgJiAEBQgcKBV9zbG90Qg0KC19zdGlja2VyX2lkQgcKBV93ZWFyQggKBl9zY2FsZUILCglfcm90YXRpb25CCgoIX3RpbnRfaWRCCwoJX29mZnNldF94QgsKCV9vZmZzZXRfeUILCglfb2Zmc2V0X3pCCgoIX3BhdHRlcm5CDAoKX2FjY291bnRpZEIJCgdfaXRlbWlkQgsKCV9kZWZpbmRleEINCgtfcGFpbnRpbmRleEIJCgdfcmFyaXR5QgoKCF9xdWFsaXR5QgwKCl9wYWludHdlYXJCDAoKX3BhaW50c2VlZEIVChNfa2lsbGVhdGVyc2NvcmV0eXBlQhEKD19raWxsZWF0ZXJ2YWx1ZUINCgtfY3VzdG9tbmFtZUIMCgpfaW52ZW50b3J5QgkKB19vcmlnaW5CCgoIX3F1ZXN0aWRCDQoLX2Ryb3ByZWFzb25CDQoLX211c2ljaW5kZXhCCwoJX2VudGluZGV4QgsKCV9wZXRpbmRleEIICgZfc3R5bGViBnByb3RvMw");

/**
 * @generated from message CEconItemPreviewDataBlock
 */
export type CEconItemPreviewDataBlock = Message<"CEconItemPreviewDataBlock"> & {
  /**
   * @generated from field: optional uint32 accountid = 1;
   */
  accountid?: number | undefined;

  /**
   * @generated from field: optional uint64 itemid = 2;
   */
  itemid?: bigint | undefined;

  /**
   * @generated from field: optional uint32 defindex = 3;
   */
  defindex?: number | undefined;

  /**
   * @generated from field: optional uint32 paintindex = 4;
   */
  paintindex?: number | undefined;

  /**
   * @generated from field: optional uint32 rarity = 5;
   */
  rarity?: number | undefined;

  /**
   * @generated from field: optional uint32 quality = 6;
   */
  quality?: number | undefined;

  /**
   * @generated from field: optional uint32 paintwear = 7;
   */
  paintwear?: number | undefined;

  /**
   * @generated from field: optional uint32 paintseed = 8;
   */
  paintseed?: number | undefined;

  /**
   * @generated from field: optional uint32 killeaterscoretype = 9;
   */
  killeaterscoretype?: number | undefined;

  /**
   * @generated from field: optional uint32 killeatervalue = 10;
   */
  killeatervalue?: number | undefined;

  /**
   * @generated from field: optional string customname = 11;
   */
  customname?: string | undefined;

  /**
   * @generated from field: repeated CEconItemPreviewDataBlock.Sticker stickers = 12;
   */
  stickers: CEconItemPreviewDataBlock_Sticker[];

  /**
   * @generated from field: optional uint32 inventory = 13;
   */
  inventory?: number | undefined;

  /**
   * @generated from field: optional uint32 origin = 14;
   */
  origin?: number | undefined;

  /**
   * @generated from field: optional uint32 questid = 15;
   */
  questid?: number | undefined;

  /**
   * @generated from field: optional uint32 dropreason = 16;
   */
  dropreason?: number | undefined;

  /**
   * @generated from field: optional uint32 musicindex = 17;
   */
  musicindex?: number | undefined;

  /**
   * @generated from field: optional int32 entindex = 18;
   */
  entindex?: number | undefined;

  /**
   * @generated from field: optional uint32 petindex = 19;
   */
  petindex?: number | undefined;

  /**
   * @generated from field: repeated CEconItemPreviewDataBlock.Sticker keychains = 20;
   */
  keychains: CEconItemPreviewDataBlock_Sticker[];

  /**
   * @generated from field: optional uint32 style = 21;
   */
  style?: number | undefined;
};

/**
 * Describes the message CEconItemPreviewDataBlock.
 * Use `create(CEconItemPreviewDataBlockSchema)` to create a new message.
 */
export const CEconItemPreviewDataBlockSchema: GenMessage<CEconItemPreviewDataBlock> = /*@__PURE__*/
  messageDesc(file_csgo_econ_preview, 0);

/**
 * @generated from message CEconItemPreviewDataBlock.Sticker
 */
export type CEconItemPreviewDataBlock_Sticker = Message<"CEconItemPreviewDataBlock.Sticker"> & {
  /**
   * @generated from field: optional uint32 slot = 1;
   */
  slot?: number | undefined;

  /**
   * @generated from field: optional uint32 sticker_id = 2;
   */
  stickerId?: number | undefined;

  /**
   * @generated from field: optional float wear = 3;
   */
  wear?: number | undefined;

  /**
   * @generated from field: optional float scale = 4;
   */
  scale?: number | undefined;

  /**
   * @generated from field: optional float rotation = 5;
   */
  rotation?: number | undefined;

  /**
   * @generated from field: optional uint32 tint_id = 6;
   */
  tintId?: number | undefined;

  /**
   * @generated from field: optional float offset_x = 7;
   */
  offsetX?: number | undefined;

  /**
   * @generated from field: optional float offset_y = 8;
   */
  offsetY?: number | undefined;

  /**
   * @generated from field: optional float offset_z = 9;
   */
  offsetZ?: number | undefined;

  /**
   * @generated from field: optional uint32 pattern = 10;
   */
  pattern?: number | undefined;
};

/**
 * Describes the message CEconItemPreviewDataBlock.Sticker.
 * Use `create(CEconItemPreviewDataBlock_StickerSchema)` to create a new message.
 */
export const CEconItemPreviewDataBlock_StickerSchema: GenMessage<CEconItemPreviewDataBlock_Sticker> = /*@__PURE__*/
  messageDesc(file_csgo_econ_preview, 0, 0);

